[package]
name = "baseview"
version = "0.1.0"
authors = [
    "William Light <git@wrl.lhiaudio.com>",
    "Charles Saracco <crsaracco@gmail.com>",
    "Mirko Covizzi <mrkcvzz@gmail.com>",
    "Micah Johnston <micah@glowcoil.com>",
    "Billy Messenger <billydm@protonmail.com>",
    "Anton Lazarev <https://antonok.com>",
    "Joakim Frostegård <joakim.frostegard@gmail.com>",
    "Robbert van der Helm <mail@robbertvanderhelm.nl>",
]
edition = "2018"
license = "MIT OR Apache-2.0"

[features]
default = []
opengl = [
    "objc2-app-kit/NSOpenGLView",
    "objc2-app-kit/objc2-open-gl",
    "uuid",
    "x11/glx",
]

[dependencies]
keyboard-types = { version = "0.6.1", default-features = false }
raw-window-handle = "0.6.2"

[target.'cfg(target_os="linux")'.dependencies]
x11rb = { version = "0.13.0", features = [
    "cursor",
    "resource_manager",
    "allow-unsafe-code",
] }
x11 = { version = "2.21", features = ["xlib", "xlib_xcb"] }
nix = "0.22.0"

[target.'cfg(target_os="windows")'.dependencies]
winapi = { version = "0.3.9", features = [
    "libloaderapi",
    "winuser",
    "windef",
    "minwindef",
    "guiddef",
    "combaseapi",
    "wingdi",
    "errhandlingapi",
    "ole2",
    "oleidl",
    "shellapi",
    "winerror",
    "windowsx",
] }
uuid = { version = "1.20.0", features = ["v4"], optional = true }

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.10.1"
objc2 = { git = "https://github.com/madsmtm/objc2.git", rev = "0c62eb96d7a3d9512f19b2c49d9dd18c8bbbb6e0" }
objc2-app-kit = { git = "https://github.com/madsmtm/objc2.git", rev = "0c62eb96d7a3d9512f19b2c49d9dd18c8bbbb6e0", features = [
    "NSResponder",
] }
objc2-foundation = { git = "https://github.com/madsmtm/objc2.git", rev = "0c62eb96d7a3d9512f19b2c49d9dd18c8bbbb6e0" }
uuid = { version = "1.20.0", features = ["v4"], optional = true }

[dev-dependencies]
rtrb = "0.2"
softbuffer = "0.3.4"

[workspace]
members = ["examples/render_femtovg"]

[lints.clippy]
missing-safety-doc = "allow"

[[example]]
name = "open_window"
test = true
doctest = true

[[example]]
name = "open_parented"
test = true
doctest = true
